name: Build project
on:
  push:
    branches: [ master ]
    paths:
      - question-bank/**
      - .github/workflows/project-build.yml

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: cd question-bank && MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED" mvn compile verify package -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dglass.platform=Monocle -Dmonocle.platform=Headless
