name: Release Build

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0

permissions:
  contents: write  # Required to create releases

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd question-bank
          # Windows syntax inside bash (MSYS) is okay with export
          export MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"
          mvn clean compile package -DskipTests

      - name: Rename JAR with tag version and platform suffix
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}               # v1.0.0
          VERSION=${TAG_NAME#v}                           # 1.0.0
          PLATFORM=$(echo "${{ matrix.os }}" | cut -d'-' -f1)  # windows / ubuntu / macos
          cd question-bank/target
          ORIGINAL_JAR=$(ls *SNAPSHOT-jar-with-dependencies.jar)
          RENAMED_JAR="question-bank-${VERSION}-${PLATFORM}.jar"
          cp "$ORIGINAL_JAR" "$RENAMED_JAR"
          echo "RENAMED_JAR_PATH=question-bank/target/$RENAMED_JAR" >> $GITHUB_ENV

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release was automatically generated from tag `${{ github.ref_name }}`.
            - Includes platform-specific JARs for Windows, Linux, and macOS.
          files: ${{ env.RENAMED_JAR_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
