name: Release Build

on:
  push:
    tags:
      - 'v*' # e.g. v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd question-bank
          mvn clean verify package \
            -Djava.awt.headless=true \
            -Dtestfx.robot=glass \
            -Dtestfx.headless=true \
            -Dprism.order=sw \
            -Dprism.text=t2k \
            -Dglass.platform=Monocle \
            -Dmonocle.platform=Headless

      - name: Rename JAR with tag version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}              # v1.0.0
          VERSION=${TAG_NAME#v}                          # 1.0.0
          cd question-bank/target
          ORIGINAL_JAR=$(ls *SNAPSHOT-jar-with-dependencies.jar)
          RENAMED_JAR="question-bank-${VERSION}.jar"
          cp "$ORIGINAL_JAR" "$RENAMED_JAR"
          echo "RENAMED_JAR_PATH=question-bank/target/$RENAMED_JAR" >> $GITHUB_ENV

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}         # This sets the title
          body: |
           This release was automatically generated from tag `${{ github.ref_name }}`.
           - Includes the JAR file with dependencies.
          files: ${{ env.RENAMED_JAR_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
